name: Outdated Parrot

on:
  pull_request:
    types:
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  parrot:
    name: Parrot outdated comments
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code for git blame
        uses: actions/checkout@v6.0.0
        with:
          fetch-depth: 0

      - name: Run parrot action
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
